import { db } from '@/lib/db'
import { generationJob } from '@/lib/db/schema'
import { getCurrentUser, apiError } from '@/lib/api'
import { getOpenAIVideo } from '@/lib/generation/providers'
import { and, eq } from 'drizzle-orm'
import { NextResponse } from 'next/server'

export const runtime = 'nodejs'
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return apiError('Sign in required', 401); const { id } = await params; const [job] = await db.select().from(generationJob).where(and(eq(generationJob.id, id), eq(generationJob.userId, user.id))); if (!job) return apiError('Job not found', 404); if (job.type === 'video' && job.status === 'running') { try { const providerVideoId = typeof job.payload?.providerVideoId === 'string' ? job.payload.providerVideoId : null; if (providerVideoId) { const video = await getOpenAIVideo(providerVideoId); const completed = video.status === 'completed'; const failed = video.status === 'failed'; const updated = { ...job, status: completed ? 'completed' : failed ? 'failed' : 'running', progress: completed ? 100 : video.progress ?? job.progress, message: completed ? 'Video ready' : failed ? (video.error?.message ?? 'Video generation failed') : 'OpenAI is generating your video', error: failed ? (video.error?.message ?? 'Video generation failed') : null, payload: { ...job.payload, providerStatus: video.status, progress: video.progress ?? job.progress } }; await db.update(generationJob).set({ status: updated.status, progress: updated.progress, message: updated.message, error: updated.error, payload: updated.payload, updatedAt: new Date() }).where(eq(generationJob.id, id)); return NextResponse.json({ job: updated }); } } catch (error) { console.error('[v0] Video status polling failed', error) } } return NextResponse.json({ job }) }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return apiError('Sign in required', 401); const { id } = await params; const action = new URL(request.url).searchParams.get('action'); const status = action === 'cancel' ? 'cancelled' : action === 'retry' ? 'queued' : null; if (!status) return apiError('Use action=retry or action=cancel'); const [job] = await db.update(generationJob).set({ status, error: null, message: status === 'cancelled' ? 'Cancelled by user' : 'Queued for retry', updatedAt: new Date() }).where(and(eq(generationJob.id, id), eq(generationJob.userId, user.id))).returning(); if (!job) return apiError('Job not found', 404); return NextResponse.json({ job }) }
